### PR TITLE
add threatview feed

### PR DESCRIPTION
**Pull request by dumprop**
Temporary solution for #650

### CODE REVIEW

**Comment by sebdraven** [comment]
I've a pb the c2 is a domain or ip. 

image

**Comment by dumprop** [comment]
Ops, yes :(

**Comment by sebdraven** [comment]
have you got a workaround or we wait an answer of threatview ?

**Comment by dumprop** [comment]
> 
> 
> You can use observable.from_string to find the good observable https://github.com/yeti-platform/yeti/blob/master/core/observables/observable.py#L137
> 
> sorry I've forgotten this API call when you have the discussion :(

I have some problems with that API call
image
Seems that there no interaction with mongo

**Comment by Malwar3Ninja** [comment]
Hello @sebdraven , @dumprop apologies for the delay in my response. i have created a separate feed for YETI which should fix the issue. Please find URL for the feed- https://threatview.io/Downloads/High-Confidence-CobaltstrikeC2_platforms.txt

I have replaced the problematic"," with "." , Let me know if this works and happy to incorporate any other suggestions.

**Comment by sebdraven** [comment]
@dumprop have you fixe your code with the new url ? :)

**Comment by dumprop** [comment]
> 
> 
> @dumprop have you fixe your code with the new url ? :)

I hope yes, but currently I need a full fresh tag logic. So I'll fix it until the end of the year

**Pull request merged**
