### PR TITLE
Update urlhaus.py

### PR DESCRIPTION
**Pull request by doomedraven**

### CODE REVIEW

**Comment by sebdraven** [comment]
you can make the change to delete first_seen variable in the definition of the method, if the code don't use it ?

**Comment by doomedraven** [comment]
done

**Comment by doomedraven** [comment]
https://github.com/yeti-platform/yeti/issues/503 there you have it @sebdraven

**Comment by sebdraven** [comment]
Ok but it's problem it's not corrected in the update method ?

**Comment by doomedraven** [comment]
nop, feed check date is different, and first seen is different, so it just flood and flood

**Comment by sebdraven** [comment]
Ok but why to have first_seen 
 self.analyze(line, first_seen) and  

   def analyze(self, line, first_seen):

if you don't use first_seen  in the method ?

**Comment by doomedraven** [comment]
removed

**Pull request merged**
