### PR TITLE
removes unused parameter from fetch_cert for circl_passive_ssl 

### PR DESCRIPTION
**Pull request by attenuatedPastie**
removes unused parameter (settings) from fetch_cert

### CODE REVIEW

**Comment by attenuatedPastie** [comment]
I'm pretty sure the settings was not used but in addition, when using the circl_passive_ssl analytics, I get this error: 

```
^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A[2024-11-22 00:15:14,789: ERROR/MainProcess] Error running task CirclPassiveSSLSearchIP
Traceback (most recent call last):
  File "/app/core/taskmanager.py", line 99, in run_task
    task.run()
  File "/app/core/schemas/task.py", line 222, in run
    self.bulk(targets)
  File "/app/core/schemas/task.py", line 228, in bulk
    self.each(observable)
  File "/app/plugins/analytics/public/circl_passive_ssl.py", line 91, in each
    ip.link_to(cert, "ip-certificate", "CirlPassiveSSL")
  File "/app/core/database_arango.py", line 528, in link_to
    "target_extended_id": target.extended_id,
  File "/app/core/database_arango.py", line 201, in extended_id
    return self._collection_name + "/" + self.id
TypeError: can only concatenate str (not "NoneType") to str
[2024-11-22 00:15:14,826: INFO/MainProcess] Task core.taskscheduler.run_task[181d5b57-27b7-4ccb-8587-26f41c7b35df] succeeded in 98.9983595770027s: None
```

Can this be fixed by simply coercing the value to a string?

**Review by sebdraven — CHANGES_REQUESTED** [review]
cert = cert.save()

**Comment by attenuatedPastie** [comment]
updated as requested @sebdraven

**Comment by sebdraven** [comment]
It's ok the bug is fixed ?

**Comment by attenuatedPastie** [comment]
I will have to test and get back to you

**Comment by sebdraven** [comment]
I'm waiting your feedback to approve and launch the CI/CD !

**Comment by attenuatedPastie** [comment]
yep it appears to be working - I have thousands of IPs that I am checking so it is still running. I haven't seen any errors so let us proceed.

**Review by tomchop — APPROVED** [review]

**Pull request merged**
