### PR TITLE
[draft] sometimes this happens - fix AttributeError: to_mongo

### PR DESCRIPTION
**Pull request by doomedraven**
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/bson/dbref.py", line 85, in __getattr__
    raise AttributeError(key)
AttributeError: to_mongo
```

### CODE REVIEW

**Comment by tomchop** [comment]
In which cases does this happen? The solution here is not to just check for the attribute but to see why it's being called on something that does not have it.

**Comment by doomedraven** [comment]
i have created new investigation, then added few nodes to graph, then went to investigations list, and when selected older had saw that issue, but all nodes was in there

**Comment by doomedraven** [comment]
i will change once i figurate which object was that one

**Comment by tomchop** [comment]
Sounds good. Just out of curiosity, can you change the PR's status to "draft"? This is to keep the number of PRs I need to review at a manageable level :D

**Comment by doomedraven** [comment]
`I'm afraid it isn't currently possible to convert a standard pull request to a draft pull request.`
https://stackoverflow.com/questions/55070723/how-do-i-change-from-a-pr-to-a-draft-pr-at-github

**Comment by tomchop** [comment]
Ugh, was worth a try. I don't know if you have permissions to re-request a review from me ?

image

**Comment by doomedraven** [comment]
i can't see that arrows, i will reopen in draft

**Pull request closed without merging**
