### PR TITLE
catch wrong type like url as ipv6, to process the rest

### PR DESCRIPTION
**Pull request by doomedraven**
related issue https://github.com/yeti-platform/yeti/issues/326

```
ERROR:observable:Value error: Invalid IPv6 URL - on: https://minhacasaminhavidacdt.blogspot[.com/
http://cdtmaster.com.br
tp://cdtmaster.com.br/Document
https://pocasideiascdt.blogspot.com/
http://minhacasaminhavidacdt.blogspot.com/
http://pocasideiascdt.blogspot.com/
http://cdtmaster.com.br/Document.mp
tcp://127.0.0.1:49356
https://minhacasaminhavidacdt.blogspot.com
https://pocasideiascdt.blogspot.com/
ERROR:observable:Value error: Invalid IPv6 URL - on: http://cdtmaster.]com.br
```

### CODE REVIEW

**Comment by tomchop** [comment]
Hmm this should not happen (URLs should not be attempted to be parsed as IPv6). What's the original URL?

**Comment by doomedraven** [comment]
fixes this url problems, https://github.com/yeti-platform/yeti/issues/326

but wouldn't it be good to catch and logging wrong value so we can faster add fix for it, and grab the rest of iocs? bcz if wihtout it it raises and exits ignorring all values

**Comment by tomchop** [comment]
Yes, but I would like to notify the user (in the UI or the API response) what observables failed to be added. Maybe we could add something to the `results` dict under an `unknown_type` key?

**Comment by doomedraven** [comment]
yes would be good

**Pull request merged**
