### PR TITLE
MISP SSL configuration updates

### PR DESCRIPTION
**Pull request by shannaniggans**
Added in the misp verify cert option to the sample config. 
i'm also going to do a PR for the documentation for showing the `.env` variables for docker.

I'm bad at github so i'm sorry for multiple branches/PRs and this replaces #1046 that i accidentally closed while trying to do another one.

### CODE REVIEW

**Comment by shannaniggans** [comment]
SORRY!!!!!!

**Review by sebdraven — APPROVED** [review]
Thanks a lot !

**Review by sebdraven — CHANGES_REQUESTED** [review]
Could you use ruff linter ? 

you can launch at the root of project like that

`ruff format .`

**Comment by shannaniggans** [comment]
I ran ruff, looked fine on misp.py, no errors and said updated.

**Comment by sebdraven** [comment]
Perfect thanks for your contribution !

**Review by sebdraven — APPROVED** [review]

**Pull request merged**
